### ISSUE TITLE
Can't import v2 models from pypi package

### ISSUE THREAD

**Issue by edo3** [DataDog/datadog-api-client-python#1002]
**Describe the bug**
I've installed `1.10.0` and tried running some examples from the website, from here to be precise https://docs.datadoghq.com/api/latest/metrics/#submit-metrics

I get the following error:
`ModuleNotFoundError: No module named 'datadog_api_client.v2.model.metric_intake_type'`

This goes for every model.

I've checked the locally installed package and run  
`grep -rn 'MetricIntakeType' .`

This yields no results

I've also downloaded both releases from here:
https://pypi.org/project/datadog-api-client/#files

unpacked them and repeated the grep, to no avail.

The models are clearly available on Github so it might be me.

**To Reproduce**
Run through a v2 example

**Expected behavior**
The models to be imported as per the example

**Environment and Versions:**
Pipenv, python
- `datadog-api-client`: `1.10`
- `python`: `3.10.2`
- `pipenv`: 3.10.2

OS: MacOS Monterey 12.3.1

**Comment by therve** [comment]
Hi,

Our public documentation reflects master, and we just merged support for that endpoint. We'll release soon with the changes included. Thanks.

**Comment by therve** [comment]
Done now, thank you.
