### ISSUE TITLE
calling `get_browser_test_result` results in `TypeError`

### ISSUE THREAD

**Issue by trondhindenes** [DataDog/datadog-api-client-python#1037]
**Describe the bug**
if calling the `get_browser_test_result` method on a test that has completed and suceeded, datadog will internally throw a `TypeError`-

Label the issue properly.

- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
See above

**Expected behavior**
an object should be returned

**Screenshots**

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:

`datadog-api-client==1.12` on python 3.9

**Additional context**
in under 2 hours I've uncovered serious bugs in both `get_browser_test_result` and `get_api_test_result`. Maybe consider testing this libraries a bit better? it's super annoying to have to revert to http clients after having spent time setting up this sdk.

**Comment by therve** [comment]
Sorry for the troubles, should be fixed by #1038 and #1039 .
