### ISSUE TITLE
Unable to use 'list_security_monitoring_signals' or 'search_security_monitoring_signals'

### ISSUE THREAD

**Issue by mtskillman** [DataDog/datadog-api-client-python#1067]
**Describe the bug**
Both of the operations mentioned in the title of this report are said to be "disabled" by the sdk despite being documented in Datadog documentation + these operations will work if you modify the source of the sdk. 

**To Reproduce**

run something like this:
...
api_instance = SecurityMonitoringApi(api_client)
response = api_instance.search_security_monitoring_signals(body=body)

**Expected behavior**
The api client should allow these operations to be performed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/55630669/175043708-ffe4a400-4f11-4728-b653-44b32b7b0fda.png)

**Environment and Versions (please complete the following information):**
datadog-api-client 1.12
python 3.8.12

**Comment by therve** [comment]
Hi,

Those operations are just out of beta, so the client has been released yet. For your version you need to add `configuration.unstable_operations["search_security_monitoring_signals"] = True` to be able to use it (and same for list). his is described in the README here: https://github.com/DataDog/datadog-api-client-python#unstable-endpoints.

Thanks

**Comment by mtskillman** [comment]
thank you @therve
