### ISSUE TITLE
No support for RUM datasource in scalar data queries

### ISSUE THREAD

**Issue by chitezh** [DataDog/datadog-api-client-python#1376]
Doc says RUM is supported - https://docs.datadoghq.com/api/latest/metrics/?code-lang=python#query-scalar-data-across-multiple-products
> This endpoint is GA for the metrics, real user monitoring (RUM) and cloud cost data sources. Support for logs is in beta. We are gradually onboarding support for more sources. If you have any feedback, contact [Datadog support](https://docs.datadoghq.com/help/).

However, it appears only `metrics` and `cloud_cost` are supported - Would you be able to update the python SDK to support this?
https://github.com/DataDog/datadog-api-client-python/blob/master/src/datadog_api_client/v2/model/metrics_data_source.py#L23

**Comment by therve** [comment]
Hi,

It seems that you need to use an event query, not a metric query. In that case the datasource is available already: https://github.com/DataDog/datadog-api-client-python/blob/master/src/datadog_api_client/v2/model/events_data_source.py,

If you take the example, replace by `MetricsScalarQuery` by `EventsScalarQuery` and you should be able to do what you want.

Let us know if that works for you, thanks,

**Comment by chitezh** [comment]
thanks, I will close for now and reopen if it doesn't work

**Comment by chitezh** [comment]
Okay, looked at this but it appears the change is not yet published - https://github.com/DataDog/datadog-api-client-python/pull/1345/files

**Comment by therve** [comment]
We just released 2.11, let us know if there is any issue. Thanks!
