### ISSUE TITLE
Type error when using `filter_from`or `filter_to` argument with SpansApi.list_spans_get()

### ISSUE THREAD

**Issue by clobraico-hf** [DataDog/datadog-api-client-python#1602]
**Describe the bug**

- I get a `datadog_api_client.exceptions.ApiException: (400)` response  when using the `filter_from` arg in the `SpansApi` despite adhering the required types (timestamp, datemath, or isoformat string).
The same string format can be used with various other Apis within the datadog_api_client.v2.api library successfully.

- Furthermore, I am unable to pass datetime objects to the `filter_from` argument, as I am able to with other APIs, such as the LogsApi. When I attempt to do this, I get 

```
datadog_api_client.exceptions.ApiTypeError: Invalid type for variable 'filter_from'. Required value type is str and passed type was datetime at ['filter_from']
```

**To Reproduce**
Steps to reproduce the Api Exception:
```
from datadog_api_client.v2 import ApiClient, Configuration
from datadog_api_client.v2.api.spans_api import SpansApi
import datetime


configuration = Configuration()
with ApiClient(configuration) as api_client:
    api_instance = SpansApi(api_client)
    response = api_instance.list_spans_get(filter_query="service:aorta env:dev",filter_to=datetime.datetime.now().isoformat())
    print(response)
```

Steps to reproduce the ApiTypeError:
```
from datadog_api_client.v2 import ApiClient, Configuration
from datadog_api_client.v2.api.spans_api import SpansApi
import datetime


configuration = Configuration()
with ApiClient(configuration) as api_client:
    api_instance = SpansApi(api_client)
    response = api_instance.list_spans_get(filter_from=datetime.datetime.now()-datetime.timedelta(minutes=120))
    print(response)
```

**Expected behavior**
Response should filter the data using the given timestamp

**Environment and Versions (please complete the following information):**
`datadog-api==2.15`
`python3.10`

**Comment by therve** [comment]
Hi,

I believe the first error you have is because you're missing the timezone. There are various ways to work around that.

Pass the timezone:

```python
tzinfo = datetime.datetime.now().astimezone().tzinfo
filter_to=datetime.datetime.now().replace(tzinfo=tzinfo).isoformat()
```

Use UTC:

```python
filter_to=datetime.datetime.utcnow().isoformat()[:-3] + "Z"
```

Use internal representation:

```python
filter_to="now"
```

Use timestamps:
```python
filter_to=str(int(datetime.datetime.now().timestamp() * 1000))
```

This is indeed different from the logs API, but we made it a string to show the other capabilities, which are somewhat hidden for logs. Does that make sense? Thanks.

**Comment by therve** [comment]
Closing for now, feel free to reopen if that doesn't work for you. Thanks.
