### ISSUE TITLE
Synthetics API GET Request Fails on UI Allowed Configuration

### ISSUE THREAD

**Issue by Patrick-Houlihan** [DataDog/datadog-api-client-python#1636]
**Describe the bug**

The bug occurs when you attempt to pull through GET request a synthetic test by ID that has a tick_every value of 600. In the UI you are able to set this value to 10m as a suggested "quick select" option, however when pulling from Datadog, this test will not be able to be retrieved due to the invalid configuration

Stack Trace identifying the value in question.

{
  "errorMessage": "Invalid value for `value` (600), must be one of [60, 300, 900, 1800, 3600, 21600, 43200, 86400, 604800]",
  "errorType": "ApiValueError",
  "stackTrace": [
    "  File \"/var/task/lambda_retagger_datadog.py\", line 184, in lambda_handler\n    monitors = get_monitors()\n",
    "  File \"/var/task/lambda_retagger_datadog.py\", line 162, in get_monitors\n    response = api_instance.get_api_test(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api/synthetics_api.py\", line 1532, in get_api_test\n    return self._get_api_test_endpoint.call_with_http_info(**kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 842, in call_with_http_info\n    return self.api_client.call_api(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 386, in call_api\n    return self.__call_api(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 214, in __call_api\n    return_data = self.deserialize(response_data, response_type, _check_type)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 307, in deserialize\n    deserialized_data = validate_and_convert_types(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1305, in validate_and_convert_types\n    converted_instance = attempt_convert_item(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1202, in attempt_convert_item\n    raise conversion_exc\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1194, in attempt_convert_item\n    return deserialize_model(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1110, in deserialize_model\n    return model_class(**kw_args)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1478, in wrapped_init\n    return fn(self, *args, **kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_api_test.py\", line 208, in __init__\n    setattr(self, var_name, var_value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 143, in __setattr__\n    self[attr] = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 316, in __setitem__\n    self.set_attribute(name, value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 119, in set_attribute\n    value = validate_and_convert_types(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1305, in validate_and_convert_types\n    converted_instance = attempt_convert_item(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1202, in attempt_convert_item\n    raise conversion_exc\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1194, in attempt_convert_item\n    return deserialize_model(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1110, in deserialize_model\n    return model_class(**kw_args)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1478, in wrapped_init\n    return fn(self, *args, **kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_test_options.py\", line 206, in __init__\n    setattr(self, var_name, var_value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 143, in __setattr__\n    self[attr] = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 316, in __setitem__\n    self.set_attribute(name, value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 119, in set_attribute\n    value = validate_and_convert_types(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1305, in validate_and_convert_types\n    converted_instance = attempt_convert_item(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1202, in attempt_convert_item\n    raise conversion_exc\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1194, in attempt_convert_item\n    return deserialize_model(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1105, in deserialize_model\n    return model_class(model_data, **kw_args)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1478, in wrapped_init\n    return fn(self, *args, **kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_tick_interval.py\", line 177, in __init__\n    self.value = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 143, in __setattr__\n    self[attr] = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 263, in __setitem__\n    self.set_attribute(name, value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 128, in set_attribute\n    check_allowed_values(self.allowed_values, (name,), value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 639, in check_allowed_values\n    raise ApiValueError(\n"
  ]
}

Label the issue properly.

I think it's somewhat severe as it's preventing the use of the get one synthetic test and the list all synthetics tests api endpoint for my use case.

- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**

1. Go to https://app.datadoghq.com/
2. Click on UX Monitoring => Synthetic Tests => New Test 
3. Create your test with the setting 10m on Section 5: Define scheduling and alert conditions
4. Use the Datadog API to request the Synthetic Test with the public ID of the one you created like below

Copied from the API Docs
"""
Get an API test returns "OK" response
"""

from datadog_api_client import ApiClient, Configuration
from datadog_api_client.v1.api.synthetics_api import SyntheticsApi

configuration = Configuration()
with ApiClient(configuration) as api_client:
    api_instance = SyntheticsApi(api_client)
    response = api_instance.get_api_test(
        public_id="public_id",
    )

    print(response)

**Expected behavior**
The expected behavior is that the details of the Synthetics test will be retrieved.

**Screenshots**
{
  "errorMessage": "Invalid value for `value` (600), must be one of [60, 300, 900, 1800, 3600, 21600, 43200, 86400, 604800]",
  "errorType": "ApiValueError",
  "stackTrace": [
    "  File \"/var/task/lambda_retagger_datadog.py\", line 184, in lambda_handler\n    monitors = get_monitors()\n",
    "  File \"/var/task/lambda_retagger_datadog.py\", line 162, in get_monitors\n    response = api_instance.get_api_test(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api/synthetics_api.py\", line 1532, in get_api_test\n    return self._get_api_test_endpoint.call_with_http_info(**kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 842, in call_with_http_info\n    return self.api_client.call_api(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 386, in call_api\n    return self.__call_api(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 214, in __call_api\n    return_data = self.deserialize(response_data, response_type, _check_type)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/api_client.py\", line 307, in deserialize\n    deserialized_data = validate_and_convert_types(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1305, in validate_and_convert_types\n    converted_instance = attempt_convert_item(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1202, in attempt_convert_item\n    raise conversion_exc\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1194, in attempt_convert_item\n    return deserialize_model(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1110, in deserialize_model\n    return model_class(**kw_args)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1478, in wrapped_init\n    return fn(self, *args, **kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_api_test.py\", line 208, in __init__\n    setattr(self, var_name, var_value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 143, in __setattr__\n    self[attr] = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 316, in __setitem__\n    self.set_attribute(name, value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 119, in set_attribute\n    value = validate_and_convert_types(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1305, in validate_and_convert_types\n    converted_instance = attempt_convert_item(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1202, in attempt_convert_item\n    raise conversion_exc\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1194, in attempt_convert_item\n    return deserialize_model(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1110, in deserialize_model\n    return model_class(**kw_args)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1478, in wrapped_init\n    return fn(self, *args, **kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_test_options.py\", line 206, in __init__\n    setattr(self, var_name, var_value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 143, in __setattr__\n    self[attr] = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 316, in __setitem__\n    self.set_attribute(name, value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 119, in set_attribute\n    value = validate_and_convert_types(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1305, in validate_and_convert_types\n    converted_instance = attempt_convert_item(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1202, in attempt_convert_item\n    raise conversion_exc\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1194, in attempt_convert_item\n    return deserialize_model(\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1105, in deserialize_model\n    return model_class(model_data, **kw_args)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 1478, in wrapped_init\n    return fn(self, *args, **kwargs)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model/synthetics_tick_interval.py\", line 177, in __init__\n    self.value = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 143, in __setattr__\n    self[attr] = value\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 263, in __setitem__\n    self.set_attribute(name, value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 128, in set_attribute\n    check_allowed_values(self.allowed_values, (name,), value)\n",
    "  File \"/opt/python/lib/python3.8/site-packages/datadog_api_client/v1/model_utils.py\", line 639, in check_allowed_values\n    raise ApiValueError(\n"
  ]
}

Setting the time to one of the selected values from the array in the stack trace yields the correct result and displays the test.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:

Version 2.16.0 of the datadog_api_client installed via pip then uploaded to AWS Lambda as a layer
The snippet shown above in steps to reproduce with a specific ID to a synthetic I have made.

**Additional context**

**Comment by therve** [comment]
Hi,

This validation was removed in #488 which was a long time ago. From the traceback it looks like you're using version 1.0.0, not 2.18.0. Can you double check? Thanks.

**Comment by Patrick-Houlihan** [comment]
Will check! I probably messed up with the version somewhere, thank you

**Comment by Patrick-Houlihan** [comment]
User error
