### ISSUE TITLE
Should depend on typing_extensions >=4.0.0

### ISSUE THREAD

**Issue by doctaweeks** [DataDog/datadog-api-client-python#1727]
**Describe the bug**
`api_client.py` imports `Self` from `typing_extensions`. However, [this was added in version 4.0.0 of typing_extensions](https://github.com/python/typing_extensions/commit/0d10fec91740924bb48cc4435df093c12a1c2368). There does not appear to be a dependency specified for `typing_extensions`. When installing using the documented instructions (`pip install datadog-api-client`) in environments with older versions of `typing_extensions`, importing `datadog_api_client` will fail at runtime:

`ImportError: cannot import name 'Self' from 'typing_extensions'`

**To Reproduce**

1. Install via pip on Ubuntu 22.04.2 LTS.
2. `import datadog_api_client`
3. Observe `ImportError`

**Comment by therve** [comment]
Thanks for the report!
