### ISSUE TITLE
Unable to set the display mode in Toplist

### ISSUE THREAD

**Issue by masterginger** [DataDog/datadog-api-client-python#1731]
**Describe the bug**
The class `datadog_api_client.v1.model.toplist_widget_definition.ToplistWidgetDefinition` does not have a field called "display_mode" or something similar. Without that field, the API is unable set the display mode (absolute vs relative) of a Toplist widget.

**To Reproduce**
Check `datadog_api_client.v1.model.toplist_widget_definition.ToplistWidgetDefinition`

**Expected behavior**
There's a "display_mode" field or something similar which allows the caller to set the display mode of the toplist widget.

**Screenshots**
N/A

**Environment and Versions (please complete the following information):**
Python 3.11.3 and the datadog-api-client 2.17.0

- services, libraries, languages and tools list and versions.

**Additional context**

**Comment by therve** [comment]
Thanks for your patience, fixed in #1733
