### ISSUE TITLE
v1 synthetics incorrectly checks for a maximum limit of 1440 on renotify_interval

### ISSUE THREAD

**Issue by mfarley281** [DataDog/datadog-api-client-python#1881]
Line 19 @ datadog_api_client/v1/model/synthetics_test_options_monitor_options.py specifies a maximum of 1440 renotify_interval. However, in the datadog GUI, things have been updated to allow custom entries of > 1440 (24 hours). A user can enter 100 days for example.

The API fails on various operations when it interacts with a test that has a renotify_interval of more than 1440 (which is completely valid, thanks to new features in the Datadog GUI).

This is in reference to the "Enable renotification" option that says:

"If this monitor stays in alert status renotify every [ x ] [ minutes/hours/seconds/days ]

It used to only allow a maximum of 24 hours, but now allows a custom entry of any period of time.

The API needs to be updated to account for this.

**Comment by nkzou** [comment]
Hi, thanks for raising the issue, and apologies for the delay. I've confirmed the discrepancy and am in the process of confirming with the api owners what a new reasonable limit is - hope to have an update for you soon.

**Comment by mfarley281** [comment]
Thanks Kevin!

**Comment by mfarley281** [comment]
I think this is still an issue

**Comment by nkzou** [comment]
Hi, v2.26.0 was released yesterday and should contain the relevant fix for this issue - please try it out and let us know if this is still an issue.
