### ISSUE TITLE
Cannot create MFA Token Global Variables

### ISSUE THREAD

**Issue by mpistrang** [DataDog/datadog-api-client-python#2026]
The low level API for `/api/v1/synthetics/variables` allows for MFA Token Global Variables to be created, however this python library does not expose this functionality.  The `SyntheticsGlobalVariable` model is lacking the `is_totp` boolean attribute required to create such variables.  The same property _is_ reflected back in the HTTP response.  I should mention `is_fido` is also missing.

I've proven locally that adding the `is_totp` attribute to the model and OpenAPI spec allows MFA Token Global Variables to be created via this library.  Is this a contribution that would be appreciated?

**Comment by Drarig29** [comment]
Hi @mpistrang! Thanks for reporting. 

Indeed, adding the support for `is_totp` is the right thing to do...

But this repository is a downstream repository where most of the code is automatically generated according to [our API specification repository](https://github.com/DataDog/datadog-api-spec), so we'll have to close your PR. We appreciate your effort though, and are sorry for the time you spent on it.

We made an internal card to tackle this in the best delays 🙇

**Comment by mpistrang** [comment]
Thanks for the info.  The linked spec repo appears to be private, but I trust you will get this fixed soon.  Thanks.

**Comment by Drarig29** [comment]
Update: we are still working on it and in review process.

**Comment by Drarig29** [comment]
**Update:** https://github.com/DataDog/datadog-api-client-python/pull/2059 was merged. The next release will contain the changes!
