### ISSUE TITLE
LogsAggregateRequest fails due to multiple oneOf exception

### ISSUE THREAD

**Issue by brandonmailhiot** [DataDog/datadog-api-client-python#360]
**Description**

The request for aggregated logs below always fails with this error:

- "datadog_api_client.v2.exceptions.ApiValueError: Invalid inputs given to generate an instance of LogsAggregateBucketValue. Multiple oneOf schemas matched the inputs, but a max of one is allowed."

```
api = logs_api.LogsApi(client)

body = LogsAggregateRequest(
        compute=[
            LogsCompute(
                aggregation=LogsAggregationFunction("count"),
            ),
        ],
        filter=LogsQueryFilter(
            query='env:production @path:"/v1/graphql" @response_time_ms:[1 TO 10000] @request_body.query:*',
        ),
        group_by=[
            LogsGroupBy(
                facet="@request_body.query",
                limit=1000,
            ),
        ]
    )

api.aggregate_logs(body)
```

**Expected behavior**
I expect to get aggregated logs.

**Environment and Versions (please complete the following information):**
  - MacOS Big Sur v11.2.1
  - Python v3.9.0
  - datadog-api-client v1.0.0-beta.5

**Comment by davidskiva** [comment]
I too have this issue.  I'm trying to aggregated logs and just return the count but get the error instead.
My code:
`        api_instance = logs_api.LogsApi(api_client)
        body = LogsAggregateRequest(
            compute=[
                LogsCompute(
                    aggregation=LogsAggregationFunction("count"),
                ),
            ],
            filter=LogsQueryFilter(
                _from="2021-04-26T09:00:00.000Z",
                query="service:auth0 tenant:kiva-prod @data.type:s",
                to="2021-04-26T09:59:59.999Z",
            ),
        )
`
My environment is:
datadog-api-clientv1.0.0b8
Python 3.8.1
MacOS 10.14.6

**Comment by souvikonline** [comment]
Am facing this issue too! I see a [commit](https://github.com/DataDog/datadog-api-client-python/commit/fb5cd51ec34cde5d07cd6d246b9c018f7ba35a2a) a couple of days back related to this, but even with the latest Github master code I see the problem.

My request body:
`body = LogsAggregateRequest(
                compute=[
                    LogsCompute(
                        aggregation = LogsAggregationFunction("count"),
                        type = LogsComputeType("total"),
                    ),
                ],
                filter=LogsQueryFilter(
                    _from = start,
                    indexes = ['main'],
                    query = "service:*",
                    to = end
                ),
                group_by=[
                    LogsGroupBy(
                        facet = "service",
                        limit = 100,
                        missing=LogsGroupByMissing(),
                        total = LogsGroupByTotal()
                    )
                ],
                options=LogsQueryOptions(
                    time_offset=1,
                    timezone="GMT"
                )
                # page=LogsAggregateRequestPage(
                #     cursor="eyJzdGFydEF0IjoiQVFBQUFYS2tMS3pPbm40NGV3QUFBQUJCV0V0clRFdDZVbG8zY3pCRmNsbHJiVmxDWlEifQ==",
                # ),
            ) `

And I see the following stack trace:

> datadog_api_client.v2.exceptions.ApiValueError: Invalid inputs given to generate an instance of LogsAggregateBucketValue. Multiple oneOf schemas matched the inputs, but a max of one is allowed.

**Comment by therve** [comment]
This should be fixed by https://github.com/DataDog/datadog-api-client-python/commit/dae960bc7e2ef9b608a799bca006531f283fe7a6. Sorry for the delay.
