### ISSUE TITLE
ImportError: cannot import name 'MetricsPayload'

### ISSUE THREAD

**Issue by shyam-habarakada** [DataDog/datadog-api-client-python#376]
**Describe the bug**
The type `MetricsPayload` described in the docs appears missing

Label the issue properly.
- Add `severity/critical` label.

**To Reproduce**
1. `python3 -m pip install datadog-api-client` 
2. Create a simple python script with,

```
#!/usr/bin/env python3

from datadog_api_client.v1 import ApiClient, ApiException, Configuration
from datadog_api_client.v1.api import metrics_api
from datadog_api_client.v1.models import Point
from datadog_api_client.v1.models import MetricsPayload

print("here...")
```

3. Run the script

```
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    from datadog_api_client.v1.models import MetricsPayload
ImportError: cannot import name 'MetricsPayload'
```

**Expected behavior**
The MetricsPayload should be imported

**Screenshots**
N/a

**Environment and Versions (please complete the following information):**
Ubuntu 18.04

**Additional context**
Trying to use the API client for the first time.

Note that I also tried installing the latest from the master branch of this repo, using `python3 -m pip install git+https://github.com/DataDog/datadog-api-client-python/` which gave me version `datadog-api-client    1.0.0b8.dev34`. The error was still there.

**Comment by therve** [comment]
Hi,

This should work now, starting with beta8 up to the latest release. Let us know if it's not the case, thanks.
