### ISSUE TITLE
Unable to pull synthetic tests to to invalid type - edge.laptop_large

### ISSUE THREAD

**Issue by inverse** [DataDog/datadog-api-client-python#509]
**Describe the bug**

Getting the following error:

```bash
Invalid value for `value` (edge.laptop_large), must be one of ['laptop_large', 'tablet', 'mobile_small', 'chrome.laptop_large', 'chrome.tablet', 'chrome.mobile_small', 'firefox.laptop_large', 'firefox.tablet', 'firefox.mobile_small']
```

It looks like the recent addition of edge broke clients due to the strict validity.

**To Reproduce**

Set up synthetic browser test with one of the edge types selected. And then call `list_tests()` on the API instance.

```python
api_instance = synthetics_api.SyntheticsApi(api_client)
res = api_instance.list_tests()
```

**Expected behavior**

All synthetic tests are listed, including ones with edge.

**Screenshots**

![image](https://user-images.githubusercontent.com/713525/124639183-27d52580-de8c-11eb-9036-1003c91e8526.png)

**Environment and Versions (please complete the following information):**

Python 3.9 with both 1.1.0 API client or master

**Additional context**

Looks to be related to this validation https://github.com/DataDog/datadog-api-client-python/blob/cdd884303b2c2d7959cff6890a7a36d1173bd0b6/src/datadog_api_client/v1/model/synthetics_device_id.py#L45

**Comment by inverse** [comment]
I haven't tried it but looks like it's been fixed.

https://github.com/DataDog/datadog-api-client-python/blob/master/src/datadog_api_client/v1/model/synthetics_device_id.py#L58

**Comment by therve** [comment]
Thanks, will release today or tomorrow.

**Comment by inverse** [comment]
Thanks!
