### ISSUE TITLE
Relationship key in list_application_keys does not return any value

### ISSUE THREAD

**Issue by yhernandez01** [DataDog/datadog-api-client-python#524]
**Describe the bug**
When getting the application keys using list_application_keys, the "relationships" key in the response is blank when there is data available.

- Low severity

**To Reproduce**
```
from datadog_api_client.v2.api import key_management_api

configuration = Configuration()
with ApiClient(configuration) as api_client:
    api_instance = key_management_api.KeyManagementApi(api_client)
    print(api_instance.list_application_keys())
```

**Expected behavior**
"relationships" key with the correct values

**Comment by therve** [comment]
I believed it's been fixed in #523
