### ISSUE TITLE
Package cannot be built from release tarball

### ISSUE THREAD

**Issue by ssgelm** [DataDog/datadog-api-client-python#858]
**Describe the bug**
I am trying to build this library from the source tarball on the release page (https://github.com/DataDog/datadog-api-client-python/releases/tag/1.9.0) and it is unbuildable due to not being a git checkout:

```
LookupError: setuptools-scm was unable to detect version for '/tmp/datadog-api-client-python-1.9.0'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

While I can obviously work around this by doing a git checkout instead or by using the wheel from PyPI, this strikes me as a bug. Either building should "just work" from the tarball or there should be a way to override `setuptools-scm`.

**To Reproduce**

1. Download tarball from https://github.com/DataDog/datadog-api-client-python/archive/refs/tags/1.9.0.tar.gz
2. Extract the tarball and cd into it.
3. Run `python setup.py install`

**Expected behavior**
Package should build

**Environment and Versions (please complete the following information):**
Debian bullseye running python 3.9

**Comment by ssgelm** [comment]
For what it's worth this can be built with the override found at https://github.com/pypa/setuptools_scm#usage-from-docker

**Comment by jirikuncar** [comment]
Hi, thank you for reporting. We recommend using released wheels from PyPI. Do you have any specific use-case where you need to install the library from sources?

**Comment by ssgelm** [comment]
Yes, the use case is building a debian package for the library so we can easily install it across many machines (managing pip that way is at best a hassle...)

**Comment by jirikuncar** [comment]
We can publish `sdist` (tar) too. Would that solve your problem?
