### ISSUE TITLE
import requests gives SSL error in datadog client

### ISSUE THREAD

**Issue by leetemil** [DataDog/datadog-api-client-python#873]
**Describe the bug**
If the line `import requests` is added to the [code example for service checks](https://docs.datadoghq.com/api/latest/service-checks/), I get an SSL error from the datadog api client. 

**To Reproduce**

1. Go to https://docs.datadoghq.com/api/latest/service-checks/
2. Run the python code example and see that it indeed works with response `{'status': 'ok'}`
3. Add `import requests` to that code example.
4. See error, with traceback ending with something as follows
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.datadoghq.eu', port=443): Max retries exceeded with url: /api/v1/check_run (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

**Expected behavior**
The import of requests should cause no change in behavior.

**Environment and Versions (please complete the following information):**
linux

- version for this project in use.
- 1.10.0

- services, libraries, languages and tools list and versions.
requests==2.22.0
pyOpenSSL==22.0.0
datadog_api_client==1.10.0
python 3.8.12

**Comment by therve** [comment]
Hi,

It looks more an issue with `pyOpenSSL` than `requests`. Can you upgrade `requests` to at least `2.24.0`? It seems to work starting that version.

**Comment by leetemil** [comment]
It works by upgrading. I also made it work with the workaround in #812 for those with older versions of requests. Thanks for taking a look @therve

**Comment by therve** [comment]
No problem! For the record, the issue comes from the `inject_into_urllib3` call which was removed in https://github.com/psf/requests/pull/5443 (and is not recommended). 

But if you're stuck with that version of requests (or want to use pyOpenSSL for some reasons), you can fix it by pass the CA certs directly, eg:

```python
from datadog_api_client.v1 import ApiClient, Configuration
import certifi

configuration = Configuration(ssl_ca_cert=certifi.where())
```
